### ISSUE TITLE
file-stream stops DLing at 25%

### ISSUE THREAD

**Issue by njaxx** [Storj/core#321] opened 2016-08-11 20:30 UTC
### Package Versions

storj@2.2.0 

Node:
```
v4.4.4
```

### Expected Behavior

It should download 100% of the video stream.  

### Actual Behavior

It consistently downloads 25% of the video.  

### Steps to Reproduce

0.  Stream the file arbitrarily onto the client machine via `storj -k 'password' stream-file 57ac99bfdd072de41857d9bf 57acbb239a1e48163c35dead > dl_of_vid.flv`
0.  Watch outputs via `nload` to see load of `~1.93 MBit/s`
0.  See that a CPU core climbs to 100% once the file begins streaming in
0.  Wait until 15% of the file is streamed, DL rate reaches 0 kbit/s and CPU remains 100%

`storj download-file` also isn't completing the download, but seems to not get through 99% it seems... and gets flaky before it stalls completely.

**Comment by NicoNet** [comment] 2016-08-12 00:40
Seems related to #310 .

**Comment by njaxx** [comment] 2016-08-12 00:46
I saw his issue before posting which is what gave me the idea to check my CPU.  Can you confirm that CPU hitting 100% on a core is abnormal?  I'm new and can't tell if it's simply the state of storj atm.

**Comment by NicoNet** [comment] 2016-08-12 01:00
Yes, for a core to hit 100% and the app just hang indefinitely is abnormal.  100% temporarily while encrypting/decrypting I find to be normal.  Thopugh, one thing I do find odd, is that if I am running multiple instances of a download and multiple instances hang, they share one core.  Two storj running and hanging would each use 50%, then 3 only use 33%, and so on.  They never use the other cores.  Which I am glad, as my Linux system doesn't take to well to having over 100% utilization.  110% for a few sec overheats and forces the system to shut down :disappointed:.

**Comment by njaxx** [comment] 2016-08-12 15:05
Btw, I'm located way out in Minnesota atm (50ms ping to nearest google).  I'm willing to share my account password and VPN access to the network I'm connecting through if that would help any.

**Comment by bookchin** [comment] 2016-08-12 18:31
Duplicate of #310

**Closed by bookchin** 2016-08-12 18:31 UTC
Labels: bug
