### ISSUE TITLE
Broken upload of file and then download of it

### ISSUE THREAD

**Issue by deadgray** [Storj/core#325] opened 2016-08-14 10:51 UTC
### Package Versions

```
npm list -g storj
/home/marek/.nvm/versions/node/v4.4.7/lib

```

### Expected Behavior

```
File uploads and I see same file size as uploaded, then I can download it
```

### Actual Behavior

```
Uploaded file size:
-rw-rw-r--  1 marek marek   20971520 Aug 14 12:34 testfile

Actual size in bucket:
 [Sun Aug 14 2016 12:49:29 GMT+0200 (CEST)] [info]   Name: tmp.0O4DNXRi78, Type: application/octet-stream, Size: 20971520 bytes, ID: 57b0384f8f266a7d4e393dd0
 [Sun Aug 14 2016 12:49:29 GMT+0200 (CEST)] [info]   Name: tmp.tdnFc2xFpq, Type: application/octet-stream, Size: 20971520 bytes, ID: 57b038b7dd072de41858a413
 [Sun Aug 14 2016 12:49:29 GMT+0200 (CEST)] [info]   Name: tmp.8r84Vd4Ocw, Type: application/octet-stream, Size: 20971520 bytes, ID: 57b0395733c81c746747b3c6
 [Sun Aug 14 2016 12:49:29 GMT+0200 (CEST)] [info]   Name: tmp.wORGPfVZlA, Type: application/octet-stream, Size: 20971520 bytes, ID: 57b039d8dd072de41858a42a
 [Sun Aug 14 2016 12:49:29 GMT+0200 (CEST)] [info]   Name: tmp.GvBLo4r96N, Type: application/octet-stream, Size: 33554432 bytes, ID: 57b03b1d8f266a7d4e393e6d
 [Sun Aug 14 2016 12:49:29 GMT+0200 (CEST)] [info]   Name: tmp.aZ5iejJvOq, Type: application/octet-stream, Size: 20971520 bytes, ID: 57b03b9e8f266a7d4e393e7c
 [Sun Aug 14 2016 12:49:29 GMT+0200 (CEST)] [info]   Name: tmp.L5H4RvahkK, Type: application/octet-stream, Size: 25165824 bytes, ID: 57b03cd7905cfece30b42d0a


Download (every time of many tries)
storj download-file 57af40b7905cfece30b400c9 57b03b1d8f266a7d4e393e6d dtest1
 [...]  > Enter your passphrase to unlock your keyring  >  ******

 [Sun Aug 14 2016 12:32:25 GMT+0200 (CEST)] [info]   Creating retrieval token...
 [Sun Aug 14 2016 12:32:25 GMT+0200 (CEST)] [info]   Resolving 6 file pointers...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 108.238.244.144:8607
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

Edit: 
File sometimes will download and is correct size (size of local file uploaded). 
I was even able to download 2 times and file are identical.
```

### Steps to Reproduce

1) Upload files of same size many times
2) Compare to bucket file sizes
3) Try to download file bad in size
4) Error

**Comment by deadgray** [comment] 2016-08-14 11:59
200MB upload try:
```
 [Sun Aug 14 2016 13:55:46 GMT+0200 (CEST)] [info]   Shard transfer completed! 4 remaining...
 [Sun Aug 14 2016 13:55:47 GMT+0200 (CEST)] [warn]   Failed to upload shard...
 [Sun Aug 14 2016 13:55:47 GMT+0200 (CEST)] [warn]   Error occured. Triggering cleanup...
 [Sun Aug 14 2016 13:55:47 GMT+0200 (CEST)] [info]   Cleaning up...
 [Sun Aug 14 2016 13:55:47 GMT+0200 (CEST)] [info]   Finished cleaning!
 [Sun Aug 14 2016 13:55:47 GMT+0200 (CEST)] [error]  No storage offers were received
 [Sun Aug 14 2016 13:55:55 GMT+0200 (CEST)] [info]   Adding shard metadata for 3dfca3fbb96e358fb2dc7214ac9b9c98c346b553 to frame
 [Sun Aug 14 2016 13:55:58 GMT+0200 (CEST)] [warn]   Failed to upload shard...
 [Sun Aug 14 2016 13:55:58 GMT+0200 (CEST)] [warn]   Error occured. Triggering cleanup...
 [Sun Aug 14 2016 13:55:58 GMT+0200 (CEST)] [info]   Cleaning up...
 [Sun Aug 14 2016 13:55:58 GMT+0200 (CEST)] [info]   Finished cleaning!
 [Sun Aug 14 2016 13:55:58 GMT+0200 (CEST)] [error]  No storage offers were received
 [Sun Aug 14 2016 13:56:11 GMT+0200 (CEST)] [info]   Adding shard metadata for 3dfca3fbb96e358fb2dc7214ac9b9c98c346b553 to frame
 [Sun Aug 14 2016 13:56:13 GMT+0200 (CEST)] [info]   Contract negotiated with: {"protocol":"0.7.1","address":"169.229.198.105","port":4030,"nodeID":"3de33d98c6d1a3e2a9933a61b1a404461284177b","lastSeen":1471175772475}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/tmp/92b9974872ef'
    at Error (native)
```
It seems that async threads aren't in good relationship :-P

**Comment by bookchin** [comment] 2016-08-14 13:35
Part of this issue is a duplicate of #237. Also note that the file size will be different after encryption. This issue is really just that the bridge client needs to add error event listener to the data channel client.

**Closed** 2016-08-16 22:24 UTC
Labels: bug, needs review
