### ISSUE TITLE
Internal spamming

### ISSUE THREAD

**Issue by 1credit** [Storj/core#317] opened 2016-08-10 16:08 UTC
### Package Versions

Replace the values below using the output from `npm list storj`. Use `npm list -g storj` if installed globally.

```
storjshare-cli@5.0.2
storj@2.1.1
```

Replace the values below using the output from `node --version`.

```
v4.4.6
```
### Expected Behavior

Storj, being a distributed network tool, should not allow shards to be stored on other nodes within the same LAN.   Experience has shown that spamming situations, similar to what has been seen with bridge nodes, can occur between different instances running on the same computer, and likely running on the same LAN.

This request would likely best be served by making it a default option, since perhaps someone will find a legitimate reason for doing so.  Or perhaps not, one could consider this a hack if done on purpose, just to increase shard counts.

Originally I considered requesting traffic be banned if it was going to the same payout address, but its fairly easy to conceive of a situation where a user is running Storj at multiple sites (I am, for one!).  Traffic between those sites would be perfectly legitimate since the different Internet connections would provide appropriate redundancy for the shards.

Technically, I'm suggesting a filter along the logic of (please forgive the pseudo code):

binary valid_ip(source_ip, destination_ip, netmask) {
    if (source_ip && netmask != destination_ip && netmask) return TRUE
    return FALSE
}

Where "&&" is a binary AND operator.

This function should be called before ANY communication is attempted to a node_id.

Note that is LAN addresses are not available within the code, the use of a node_id's public address would server the same purpose.

```

```
### Actual Behavior

When running multiple nodes within the same LAN communication between the nodes can cause spamming issues (potentially a source of internal DDOS attack type activity).  Please contact @Deadgray for examples he has seen.

```

```
### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.
1. ...
2. ...
3. ...

**Comment by deadgray** [comment] 2016-08-10 16:15
You can reproduce this connection spam artificially:
1) Have 2 nodes, A & B
2) On node B, add node A in config on top of seeds[] list. 
3) Wait some undefined time to see messages A<-->B run like crazy.

**Comment by littleskunk** [comment] 2016-08-10 16:23
What message are they sending? Can you upload a logfile please or send it via mattermost?

**Comment by littleskunk** [comment] 2016-08-13 09:53
I can predict the log you would see. It will be the same result as https://github.com/Storj/storjshare-cli/issues/122#issuecomment-239612014

The problem is a bad routing table because of https://github.com/Storj/core/issues/221.
Node B is even more complicated because the FIND_NODE send to node A will give node B a bad copy of a bad routing table.
Node B is now thinking node A would be his neighbor. Time to send him any message we receive. Add node C and D the same way and node A will get a problem.

Solution: Solving https://github.com/Storj/core/issues/221 will allow node B, C and D to start with a perfect routing table. They will send out messages to there close neighbors and not to node A. If node A and B are close to each other they would send messages to each other but that is fine. If you block them, you will get the same messages a second later from any other neighbor node.

**Comment by 1credit** [comment] 2016-08-13 09:56
Thinking about the health of the network and future hackers, what is to prevent someone from using a vanity type generator to create hundreds of very close nodeids to run on the same server, using the same disk array?  All would favor talking to each other even with a good routing table, wouldn't you?  I am running 40 nodes (with a bit of swapping) on an old DDR2 memory class quad core with only 4GB of memory, but a lot of disk.  It wouldn't take much to configure a machine that could do 100...

**Comment by littleskunk** [comment] 2016-08-13 11:46
I am not sure.  -> https://github.com/Storj/core/issues/323

**Comment by littleskunk** [comment] 2016-08-20 10:02
Please try again with the latest core release. It should be fixed now.

**Comment by super3** [comment] 2016-09-14 19:05
@1credit @littleskunk Stated that this was fixed a month ago. Please let me know if it is not, and I can re-open.

**Comment by 1credit** [comment] 2016-09-14 19:50
@deadgray You had the original example.  Are you still seeing this?

**Comment by 1credit** [comment] 2016-09-22 00:07
Would like to update this request with something similar and perhaps easier to implement:  Don't allow two nodes with the same public address to talk to each other.  This is fairly easily spamable by settting up a bunch of cnames, but would have beneficial aspect for those trying to play nice.

**Comment by littleskunk** [comment] 2016-09-22 09:59
@1credit 
No that is not possible. That way we would implement a new bug. Lets take an example.

Lets start a few nodes. You are running node A, B, C, E, F and G. I am node D.
In a perfect world after solving https://github.com/Storj/core/issues/221 every node has a perfect routing table and will talk to his neighboors. D would talk with C and E and your node B would talk to localhost A and C.

Now your solution. Lets block the localhost communication.
A, B, C, E, F and G would all spam my node D because they are not allowed to communicate with there own neighboors. 
B is not allowed to send a message to C. B will send the message to D and D will relay to C. C will get the message anyway. -> Your fix is useless. Still the same traffic but this time not localhost...

A, B, E and F will not receive any contracts. Your solution would block them. In a perfect world D would relay the contract to C and C to B and B to A. Everyone can send an offer. With your fix C is not allowed to relay the message. B and A will never receive the contract.

**Comment by 1credit** [comment] 2016-09-22 11:32
Your example presumes I have 6 nodes and you have node 7 in a world of 7 nodes.  

Without something like this being implemented the risk of many mirror copies existing within the same physical space is rather high - not a good thing.

**Comment by littleskunk** [comment] 2016-09-22 13:51
Not possible that way. Even your solution would not stop me from running 100 nodes with 100 different IP address on the same host. I can remove any line of code on the client. No way to implement it on the client side. I will send telemetry reports with different IP address. Renter and bridge are not able to detect my 100 nodes. They will look like 100 different hosts.

We will implement this solution: https://github.com/Storj/sips/blob/master/sip-0002.md

**Comment by 1credit** [comment] 2016-09-22 21:48
Your missing the point of filtering on the public IP address, not the host address, although CNAMEs could get you around that.  I'm less concerned about the hacker than I am protecting farmers data by default.

**Comment by bookchin** [comment] 2016-09-22 23:08
Yes we should not send messages to nodes who identify themselves with a matching public address, just like we do not send messages who claim to be from 127.0.0.1 or localhost.

**Comment by 1credit** [comment] 2016-09-22 23:43
Thank you Gordon.  Must say however, I've recently seen a ton of 127.0.0.1 traffic when I crank up all 140 nodes.

**Comment by bookchin** [comment] 2016-09-22 23:46
Are you tunneling any connections? That will happen as the gateways server will forward messages to the local tunnel server.

**Comment by 1credit** [comment] 2016-09-22 23:48
Ah, yes I am.  But its to network server ports, not tunnel ports.  From a netstat snapshot I took yesterday:

http://puu.sh/rkyvK/aa55200339.png

**Comment by bookchin** [comment] 2016-09-22 23:58
Are any of *your* nodes tunneled?

**Comment by 1credit** [comment] 2016-09-23 00:04
No, all have static IP ports and the same public ip.

**Comment by yuilleb** [comment] 2016-10-15 02:25
This is a lot to read and take in, but I think I have a handle on it. I believe the traffic @1credit is seeing is legitimate.

This is a _good thing_. The ideal situation for @1credit would be if 1 of his nodes received all PUBLISH messages from the internet while the remaining 99 other nodes were relayed these internally from this 1 node. Obviously this would take some special coding to make something like this work, but the main point is, the more traffic @1credit can keep routing on his localhost interface the **better**.

I think @1credit's concern is that shards are actually being passed between his nodes. I don't believe this is the case, but if there are logs showing this then I don't have a proper understanding of how storj works yet.

I personally can't see any problems with nodes communicating with each other over a loopback interface, especially when that's more efficient than routing out to nodes on the internet. As I said, I'd argue this is exactly what you want to see.

**Closed** 2017-03-31 15:47 UTC
Labels: discussion
