### ISSUE TITLE
too many active transfers, not sending offer

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#591] opened 2016-12-12 08:14 UTC
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
CLI
StorjShare: 9.0.3
Core:       6.0.7
Protocol:   1.0.0
```

Replace the values below using the output from `node --version`.

```
v6.9.2
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

4 active data channel. Sending new OFFER as soon as data channel closed.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

2 hours sending OFFER and than silence for the next 6 hours.
```
{"level":"info","message":"sending OFFER message to {\"userAgent\":\"6.0.7\",\"protocol\":\"1.0.0\",\"hdKey\":\"xpub6BKMrtzRrthaCvD4yKg2NMre3sr2sqAf7JtYPfQ9rxzxLwugGZ71qvWJnJtzzfrXmG2rmhEdKXdYbXwdJE6jSmXDwfC53QDpVDt1LKUfnMC\",\"hdIndex\":1601,\"address\":\"server016.storj.dk\",\"port\":5001,\"nodeID\":\"ad0f295d675d07f865e3d9495a6350c70fd34b8b\",\"lastSeen\":1481506230013}","timestamp":"2016-12-12T01:30:30.013Z"}
...
{"level":"debug","message":"received contract offer...","timestamp":"2016-12-12T07:34:03.552Z"}
{"level":"debug","message":"pending offers 0 is less than concurrency true: 1","timestamp":"2016-12-12T07:34:03.552Z"}
{"level":"debug","message":"renter is whitelisted: true","timestamp":"2016-12-12T07:34:03.553Z"}
{"level":"warn","message":"too many active transfers, not sending offer","timestamp":"2016-12-12T07:34:03.553Z"}
{"level":"debug","message":"negotiator returned: false","timestamp":"2016-12-12T07:34:03.553Z"}
{"level":"debug","message":"we have enough free space: true","timestamp":"2016-12-12T07:34:03.553Z"}
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Farm for a few hours.
2. Grep logfile for `OFFER\|too many active transfers'

**Comment by deadgray** [comment] 2016-12-12 08:47
Confirming, after short time all usefull traffic is stopped, we have idle node.

**Comment by bookchin** [comment] 2016-12-12 15:47
I found the issue. In the event that a client terminated the connection while transferring the shard, we don't decrement the count and cleanup. This can cascade to other farmers as well - if a shard fails to upload after the retry count, the CLI terminates causing this to happen to all farmers with pending transfers. It only takes a few to take the network effectively offline. 

I have fix staged and am running some final tests. Patch incoming.

**Closed** 2016-12-12 16:21 UTC
Labels: needs review

**Comment by yuilleb** [comment] 2016-12-13 07:32
```
$ storjshare --version
StorjShare: 9.0.5
Core:       6.0.8
Protocol:   1.0.0
```

Issue still exists with 6.0.8. There must be somewhere else that the counter is not being decremented.

```
{"level":"debug","message":"received contract offer...","timestamp":"2016-12-13T07:31:07.322Z"}
{"level":"debug","message":"pending offers 0 is less than concurrency true: 1","timestamp":"2016-12-13T07:31:07.322Z"}
{"level":"warn","message":"too many active transfers, not sending offer","timestamp":"2016-12-13T07:31:07.322Z"}
{"level":"debug","message":"negotiator returned: false","timestamp":"2016-12-13T07:31:07.322Z"}
{"level":"debug","message":"we have enough free space: true","timestamp":"2016-12-13T07:31:07.322Z"}
```

**Comment by littleskunk** [comment] 2016-12-13 09:38
@yuilleb full logfile please.

**Comment by yuilleb** [comment] 2016-12-13 16:23
I don't have a full log file, but here's some more relevant info. I added how many active transfers there are to the debug message when it says "too many". Turns out somehow storj is allowing more than the set concurrent transfers to take place. In my node I have it set to 1 and after adding this debug message I saw multiple times where it had 6 active transfers taking place. Now that my node has stopped accepting new transfers it seems to be stuck with 4 actives. As far as I can figure it never should have allowed more than 1 to begin with.

```
{"level":"debug","message":"received contract offer...","timestamp":"2016-12-13T08:20:33.747Z"}
{"level":"debug","message":"pending offers 0 is less than concurrency true: 1","timestamp":"2016-12-13T08:20:33.747Z"}
{"level":"warn","message":"too many active transfers 4, not sending offer","timestamp":"2016-12-13T08:20:33.747Z"}
{"level":"debug","message":"negotiator returned: false","timestamp":"2016-12-13T08:20:33.748Z"}
{"level":"debug","message":"we have enough free space: true","timestamp":"2016-12-13T08:20:33.748Z"}
```

**Comment by bookchin** [comment] 2016-12-13 16:58
The backoff limit is for offers, not transfers. You will serve downloads and uploads you are contracted for, period. You just won't send offers for new contracts (which generally is followed by a new transfer) when this threshold is exceeded.

**Comment by yuilleb** [comment] 2016-12-13 17:08
I have concurrency set to 1. In this instance I would figure I should never see the variable `activeTransfers` be greater than 1 right? Perhaps I'm actually sending more than 1 outstanding offer at any given time?

This might be a side issue, as I was originally just trying to track down why `activeTransfers` was larger than `_offerBackoffLimit`.

Is `_offerBackoffLimit` not the same as the concurrency setting?

In any rate this original issue posted by @littleskunk should still be open as my node stops sending offers for publish messages after an hour or so even after upgrading to 6.0.8.

**Comment by littleskunk** [comment] 2016-12-13 17:19
Renter would like to upload a file to you. -> activeTransfers 1. Stop sending OFFER.
Upload finished. -> activeTransfer 0. Start sending new OFFER.
Renter request 10 downloads. -> activeTransfer 10. Stop sending OFFER until all downloads finished.

What do you expect? What should your farmer do if the Renter request 10 Downloads? It will only stop sending OFFER. It will not stop the renter requesting downloads.

Without a logfile it will be hard for us to reproduce the issue.

**Comment by yuilleb** [comment] 2016-12-13 17:46
My expected behavior was if I set concurrency to 1 then it would only send 1 pending offer at a time. Otherwise if I send 30 offers then I could end up with 30 concurrent uploads to my farmer, in which case I don't understand the point of the concurrency option at all.

As for the original issue, reproducing is not hard. It happens just like it did before this update within a few hours of starting farming. Just turn your concurrency down low like 1 to get it to happen. I had my farmer running in screen so there was no log file.

**Comment by littleskunk** [comment] 2016-12-13 18:05
Now you lost me. Concurrency or offerBackoffLimit? That are 2 different options.

Without your logfile it is hard for us to reproduce. My farmer was running for hours yesterday without any problems. If you can reproduce the issue please do it and send stdout into a logfile. That will allow us to look into it and fix it.

**Comment by yuilleb** [comment] 2016-12-13 18:49
Ahh I did not realize that. Where is offerBackoffLimit set?

OK, I'll write the output to a file and run it again. It should take about an hour or so before it I should see something.

**Comment by littleskunk** [comment] 2016-12-13 18:57
Keep it running a few hours more. It is expected to hit the Limit after some time. Even one hour without any OFFER message is possible. (Renter request 10 downloads and you have to finish them all)
It would be a bug if you don't see any OFFER message for several hours.

offerBackoffLimit is set to 4 and not available on CLI or GUI config. I am working on a pull request for CLI config but I had no time to test it.

**Comment by yuilleb** [comment] 2016-12-13 19:02
OK thanks, I'll let it keep running for at least 2 hours after it stops sending offers.
