### ISSUE TITLE
Not getting response from farmer when downloading files.

### ISSUE THREAD

**Issue by NutterzUK** [Storj/core#355] opened 2016-08-20 10:03 UTC
### Package Versions

Bridge 3.0.4
Connecting using the Java client.

### Expected Behavior

I upload a file, this seems to work. I then get a token to download it and connect to a farmer. I send this token, and expect a response containing the bytes of the file.

### Actual Behavior

The farmer never responds, then eventually closes the connection. Here is the log from the output of the Java client, it should be easy enough to follow:
`
**1) Get a token for a file previously uploaded:**

8 * Client out-bound request
8 > GET http://api.storj.io/buckets/57932e1488fc0f4839e44a49/files/57b8296a8da3cf3071e45d9c?limit=10&skip=0
8 > Accept: application/json
8 > Authorization: basic [REDACTED]
8 > x-token: 2315f6e820dd0923ce3b11cb122a3223f0e9a4a7e57674888224a46d2abd7afa

8 * Client in-bound response
8 < 200
8 < Server: nginx/1.10.0
8 < ETag: W/"120-Rb+HD6WId8uvgz6EiS7j7g"
8 < Access-Control-Allow-Credentials: true
8 < Connection: keep-alive
8 < Vary: Origin
8 < Content-Length: 288
8 < Date: Sat, 20 Aug 2016 09:56:59 GMT
8 < X-Powered-By: Express
8 < Content-Type: application/json; charset=utf-8
8 < 
[{"token":"069be92fd939843443dafb151630c5638033be20","hash":"b3de04e77ccc982070be76c56cc71015d3e13ea8","farmer":{"protocol":"0.8.0","address":"server.remsysuk.com","port":4000,"nodeID":"b9ff536a3a750c9ae6c30b5ea3c5c9d70915ef80","lastSeen":1471687019379},"operation":"PULL","size":136356}]

**2) Connect to the farmer and send token**
Aug 20, 2016 10:57:00 AM storj.io.client.DefaultStorjClient downloadFile
INFO: CONNECTING TO: ws://server.remsysuk.com:4000
Aug 20, 2016 10:57:01 AM storj.io.client.websockets.WebsocketFileRetriever onOpen
INFO: Opened
Aug 20, 2016 10:57:01 AM storj.io.client.websockets.WebsocketFileRetriever onOpen
INFO: sent: {"token":"069be92fd939843443dafb151630c5638033be20","hash":"b3de04e77ccc982070be76c56cc71015d3e13ea8","operation":"PULL"}

**3) No message received, some time later, socket closed**
Aug 20, 2016 10:57:31 AM storj.io.client.websockets.WebsocketFileRetriever onClose
INFO: Closed Websocket: NORMAL_CLOSURE Closing`

### Steps to Reproduce

Download the storj java client available here https://github.com/NutterzUK/storj-java-bridge-client and try to download a file.

**Comment by NutterzUK** [comment] 2016-08-20 10:04
Note the auth token is sent in the exact same way it is sent when uploading files.

**Comment by NutterzUK** [comment] 2016-08-20 11:03
I should add that i've tried with the CLI, and it's hanging:
 [Sat Aug 20 2016 11:55:08 GMT+0100 (GMT Summer Time)] [info]   Creating retrieval token...
 [Sat Aug 20 2016 11:55:12 GMT+0100 (GMT Summer Time)] [info]   Resolving file pointer...
 [Sat Aug 20 2016 11:55:14 GMT+0100 (GMT Summer Time)] [info]   Downloading file from 1 channels.

Then nothing. I've been on this for about 5 mins.

**Comment by bookchin** [comment] 2016-08-20 12:04
Is this happening consistently with all files? You may have just stored the file on a misbehaving farmer.

**Comment by NutterzUK** [comment] 2016-08-20 13:54
With my Java client it's consistent. I haven't tested much with the CLI but will do and will get back to you.

**Comment by NutterzUK** [comment] 2016-08-20 14:28
Seems consistent with the CLI too.

**Comment by NutterzUK** [comment] 2016-08-20 21:04
How can it be that request 3 gives me the farmer: 73.65.94.164:4000
And as soon as i've uploaded the shard, to only one farmer then I request the file (request 7), I get a pointer to farmer: server.remsysuk.com:4000


1 * Client out-bound request
1 > GET http://api.storj.io/buckets
1 > Accept: application/json
1 > Authorization: basic XXX
1 * Client in-bound response
1 < 200
1 < Server: nginx/1.10.0
1 < ETag: W/"b0-KEhUbGgVjxqKiTVx6aFwIg"
1 < Access-Control-Allow-Credentials: true
1 < Connection: keep-alive
1 < Vary: Origin
1 < Content-Length: 176
1 < Date: Sat, 20 Aug 2016 20:13:17 GMT
1 < X-Powered-By: Express
1 < Content-Type: application/json; charset=utf-8
1 < 
[{"user":"nutterzuk@gmail.com","created":"2016-08-20T15:32:32.964Z","name":"My Bucket","pubkeys":[],"status":"Active","transfer":0,"storage":0,"id":"57b87810d8c984a21821f416"}]
2 * Client out-bound request
2 > POST http://api.storj.io/frames
2 > Accept: application/json
2 > Authorization: basic XXX
2 * Client in-bound response
2 < 200
2 < Server: nginx/1.10.0
2 < ETag: W/"87-UP9CBvqr2Pf7/hy6UtLQNg"
2 < Access-Control-Allow-Credentials: true
2 < Connection: keep-alive
2 < Vary: Origin
2 < Content-Length: 135
2 < Date: Sat, 20 Aug 2016 20:13:18 GMT
2 < X-Powered-By: Express
2 < Content-Type: application/json; charset=utf-8
2 < 
{"user":"nutterzuk@gmail.com","shards":[],"size":0,"locked":false,"created":"2016-08-20T20:13:18.101Z","id":"57b8b9de6d9185d5172ae251"}
Aug 20, 2016 9:13:19 PM storj.io.restclient.rest.StorjRestClient addShardToFrame
INFO: Attempting to negotiate shard contract, attempt 1 of 8
3 * Client out-bound request
3 > PUT http://api.storj.io/frames/57b8b9de6d9185d5172ae251
3 > Accept: application/json
3 > Authorization: basic XXX
3 > Content-Type: application/json
{"index":0,"hash":"b3de04e77ccc982070be76c56cc71015d3e13ea8","size":136356,"tree":["73b16d98c194273286026354f7cd4cd6bc6574b7","2991e1a40a2266bcf93d39d4aaf3df275b5f139a","8cef0a3384c124041a03f7460fe46dd1ce866775","eed74a303c4351f7ded9cd69526fd84d24f539d9","35367f3df28c3ce3276c3ba96785a4e3b362e8e2","a7592584224b0d365eb9674f328774a3aefac137","18c8633550cc292cfb5b5acdf46e16fc2da65989","1538e10b40da4d07bb711036e04910b1a77c3070"],"challenges":["30770009407a23f585c398a57ba07db9","b7d7fe5aaeb37071cfdc7272c4cd6824","f69c14044652055f3936383cb8dc1fdf","c4dd68f39500c5fe1174c8be9ce8fbd8","7af7fc033d8b489f6613d27174dec337","3dc4a51b2de090348a4b2a7d4abf2c3e","5e5d4c7ac81efe124cab79f249a87992","7b20067f7695830060e225d8f17e8cb6"]}
3 * Client in-bound response
3 < 200
3 < Server: nginx/1.10.0
3 < ETag: W/"109-qJYlM9mdFlEyGNjBsmWRBQ"
3 < Access-Control-Allow-Credentials: true
3 < Connection: keep-alive
3 < Vary: Origin
3 < Content-Length: 265
3 < Date: Sat, 20 Aug 2016 20:13:19 GMT
3 < X-Powered-By: Express
3 < Content-Type: application/json; charset=utf-8
3 < 
{"hash":"b3de04e77ccc982070be76c56cc71015d3e13ea8","token":"0cd60e913a09f04a0a9a45023d32576359ff8955","operation":"PUSH","farmer":{"protocol":"0.8.0","address":"73.65.94.164","port":4000,"nodeID":"ba530a4579399bbec8241e244a2b19e8a123ff6b","lastSeen":1471723998893}}
4 * Client out-bound request
4 > GET http://api.storj.io/frames/57b8b9de6d9185d5172ae251
4 > Accept: application/json
4 > Authorization: basic XXX
4 * Client in-bound response
4 < 200
4 < Server: nginx/1.10.0
4 < ETag: W/"a6-sxlhmBYlpXzTpklRukYOfQ"
4 < Access-Control-Allow-Credentials: true
4 < Connection: keep-alive
4 < Vary: Origin
4 < Content-Length: 166
4 < Date: Sat, 20 Aug 2016 20:13:19 GMT
4 < X-Powered-By: Express
4 < Content-Type: application/json; charset=utf-8
4 < 
{"user":"nutterzuk@gmail.com","shards":["57b8b9de1ffd5ac71f694f83"],"size":136356,"locked":false,"created":"2016-08-20T20:13:18.101Z","id":"57b8b9de6d9185d5172ae251"}
Aug 20, 2016 9:13:21 PM storj.io.client.websockets.WebsocketShardSender onClose
INFO: Websocket closed with reasonCloseReason[1000,Consignment completed]
5 * Client out-bound request
5 > POST http://api.storj.io/buckets/57b87810d8c984a21821f416/files
5 > Accept: application/json
5 > Authorization: basic XXX
5 > Content-Type: application/json
{"mimetype":"image/jpeg","filename":"cat.jpg","size":136368,"frame":"57b8b9de6d9185d5172ae251"}
5 * Client in-bound response
5 < 200
5 < Server: nginx/1.10.0
5 < ETag: W/"d9-qgukBFdEdVNuw5Edknk8Mw"
5 < Access-Control-Allow-Credentials: true
5 < Connection: keep-alive
5 < Vary: Origin
5 < Content-Length: 217
5 < Date: Sat, 20 Aug 2016 20:13:22 GMT
5 < X-Powered-By: Express
5 < Content-Type: application/json; charset=utf-8
5 < 
{"bucket":"57b87810d8c984a21821f416","frame":"57b8b9de6d9185d5172ae251","name":"cat.jpg","renewal":"2016-11-18T20:13:22.405Z","mimetype":"image/jpeg","filename":"cat.jpg","id":"57b8b9e26738047f2c416c04","size":136356}
Aug 20, 2016 9:13:23 PM storj.io.client.DefaultStorjClient downloadFile
INFO: C:\Users\steve\AppData\Local\Temp\temp6737313054818280669encrypted
6 * Client out-bound request
6 > POST http://api.storj.io/buckets/57b87810d8c984a21821f416/tokens
6 > Accept: application/json
6 > Authorization: basic XXX
6 > Content-Type: application/json
{"operation":"PULL"}
6 * Client in-bound response
6 < 201
6 < Server: nginx/1.10.0
6 < ETag: W/"f0-+DxxpxQuHQlJCyVdGPQxYQ"
6 < Access-Control-Allow-Credentials: true
6 < Connection: keep-alive
6 < Vary: Origin
6 < Content-Length: 240
6 < Date: Sat, 20 Aug 2016 20:13:22 GMT
6 < X-Powered-By: Express
6 < Content-Type: application/json; charset=utf-8
6 < 
{"bucket":"57b87810d8c984a21821f416","operation":"PULL","expires":"2016-08-20T20:18:22.617Z","token":"2bfb425d8861c061103b8fbee8d0c98518a86b7c42b2339cbb77d9431ff9828e","id":"2bfb425d8861c061103b8fbee8d0c98518a86b7c42b2339cbb77d9431ff9828e"}
7 * Client out-bound request
7 > GET http://api.storj.io/buckets/57b87810d8c984a21821f416/files/57b8b9e26738047f2c416c04?limit=10&skip=0
7 > Accept: application/json
7 > Authorization: basic XXX
7 > x-token: 2bfb425d8861c061103b8fbee8d0c98518a86b7c42b2339cbb77d9431ff9828e
7 * Client in-bound response
7 < 200
7 < Server: nginx/1.10.0
7 < ETag: W/"120-Y2FSevWZjaEOun4J4x9RwA"
7 < Access-Control-Allow-Credentials: true
7 < Connection: keep-alive
7 < Vary: Origin
7 < Content-Length: 288
7 < Date: Sat, 20 Aug 2016 20:13:23 GMT
7 < X-Powered-By: Express
7 < Content-Type: application/json; charset=utf-8
7 < 
[{"token":"b116a9ccd2d035bee22a8b97ef8d5eb621e3b53a","hash":"b3de04e77ccc982070be76c56cc71015d3e13ea8","farmer":{"protocol":"0.8.0","address":"server.remsysuk.com","port":4000,"nodeID":"b9ff536a3a750c9ae6c30b5ea3c5c9d70915ef80","lastSeen":1471724002968},"operation":"PULL","size":136356}]

**Comment by NutterzUK** [comment] 2016-08-21 21:24
This isn't an issue with the CLI, I can download using the CLI (I was on an old version before).

However, I am still not getting a response back from the farmer with the Java client.

The last message on the farmer's log is:
{"level":"info","message":"data channel connection opened","timestamp":"2016-08-21T13:09:36.007Z"}

This is when the client issues the token, and then nothing is heard back.

If I was to have a wild guess, something gets lost inside this if-statement:
https://github.com/Storj/core/blob/db24a6c653e6653cb4844ef3374aadf69f3dcd13/lib/data-channels/server.js#L286

**Comment by MeijeSibbel** [comment] 2016-08-21 22:23
I can confirm this, the upload of large files also hangs at the same point.

**Comment by aleitner** [comment] 2016-08-22 18:06
This may have been happening due to one of our mongo instances being down. This would result in no response for token. Can you verify this is still happening?

**Comment by NutterzUK** [comment] 2016-08-22 18:15
This is still happening. I'm a little bit confused also why when creating the shard I am given one farmer to upload to, then when retrieving the shard it's a different one (Does the bridge tell it to mirror them by default?) - e.g compare the response to request 5 to the response in request 9. If this is wrong, it may be a bridge issue. If it's right, it may be a farmer issue. Or... it may still be a problem with my Java client. 

However, I do know that if I send an invalid token to the farmer, it does reject it and close the connection. This makes me think the token I am sending is correct and valid... but it just doesn't send me any data back.

1 * Client out-bound request
1 > GET http://api.storj.io/buckets
1 > Accept: application/json
1 > Authorization: basic XXX
1 * Client in-bound response
1 < 200
1 < Server: nginx/1.10.0
1 < ETag: W/"39a-NCkcvNVpmozRT4qMho7TKg"
1 < Access-Control-Allow-Credentials: true
1 < Connection: keep-alive
1 < Vary: Origin
1 < Content-Length: 922
1 < Date: Mon, 22 Aug 2016 18:10:04 GMT
1 < X-Powered-By: Express
1 < Content-Type: application/json; charset=utf-8
1 < 
[{"user":"nutterzuk@gmail.com","created":"2016-08-21T12:14:11.898Z","name":"skunk","pubkeys":["02e8aaa6a969ea8c26fb09051c153e3c1aa9d2119fad5b900494c7f0c64969b4cb"],"status":"Active","transfer":30,"storage":10,"id":"57b99b136738047f2c421cf2"},{"user":"nutterzuk@gmail.com","created":"2016-08-21T19:54:28.149Z","name":"abc","pubkeys":[],"status":"Active","transfer":0,"storage":0,"id":"57ba06f456123d6837708296"},{"user":"nutterzuk@gmail.com","created":"2016-08-21T19:55:28.866Z","name":"asedsad","pubkeys":[],"status":"Active","transfer":0,"storage":0,"id":"57ba0730c7f1854e44a4fa56"},{"user":"nutterzuk@gmail.com","created":"2016-08-21T19:58:37.662Z","name":"aaa","pubkeys":[],"status":"Active","transfer":0,"storage":0,"id":"57ba07ed6738047f2c423d5c"},{"user":"nutterzuk@gmail.com","created":"2016-08-21T20:08:06.610Z","name":"aaa","pubkeys":[],"status":"Active","transfer":0,"storage":0,"id":"57ba0a2656123d683770830c"}]
2 * Client out-bound request
2 > POST http://api.storj.io/frames
2 > Accept: application/json
2 > Authorization: basic XXX
2 * Client in-bound response
2 < 200
2 < Server: nginx/1.10.0
2 < ETag: W/"87-t04wAgylYa0fFHUlMDACoQ"
2 < Access-Control-Allow-Credentials: true
2 < Connection: keep-alive
2 < Vary: Origin
2 < Content-Length: 135
2 < Date: Mon, 22 Aug 2016 18:10:05 GMT
2 < X-Powered-By: Express
2 < Content-Type: application/json; charset=utf-8
2 < 
{"user":"nutterzuk@gmail.com","shards":[],"size":0,"locked":false,"created":"2016-08-22T18:10:05.181Z","id":"57bb3ffdc7f1854e44a56085"}
Aug 22, 2016 7:10:06 PM storj.io.restclient.rest.StorjRestClient addShardToFrame
INFO: Attempting to negotiate shard contract, attempt 1 of 8
3 * Client out-bound request
3 > PUT http://api.storj.io/frames/57bb3ffdc7f1854e44a56085
3 > Accept: application/json
3 > Authorization: basic XXX
3 > Content-Type: application/json
{"index":0,"hash":"b3de04e77ccc982070be76c56cc71015d3e13ea8","size":136356,"tree":["502fb33e68851a4a05d6055d73d3ddd59b6cbb55","5b6b5fc81cc721fab5fe5fba9cf232437084437f","446a96efb7cb2f90083e781340d71802d25fcbb7","20d4db024df34eef03c39a7138f67a99bd48bfaf","37886fce0dd47ac50240dcc9fcc7d26c3ae9faec","296be770058c067e7c5d62000499f184e937cacd","f7b5850fb835a471fdcad6d677b3da6702544f88","a30de95c04ff3ba2712227b32ae340649a6ab3be"],"challenges":["f7b7c6dd86152ac41b6555f959c46425","7623b13572d6577da28a7f1fb3fcc1a4","cca4e6c196e1aee5f155d50df38ae503","d57c3518b9416bca545b9f5d493a0136","6a5e6fcaefbf1a6ab48de8b8ded04daa","3b4d70dbb7a96e1e63c6a4cb4e3eb1a2","edca9a987345aee881481a2cb0ca7258","e28c7d52eec776c910af144e2724c5df"]}
3 * Client in-bound response
Aug 22, 2016 7:10:21 PM storj.io.restclient.rest.StorjRestClient addShardToFrame
3 < 500
INFO: Failed with reason: PUT http://api.storj.io/frames/57bb3ffdc7f1854e44a56085 returned a response status of 500 Internal Server Error
3 < Server: nginx/1.10.0
Aug 22, 2016 7:10:21 PM storj.io.restclient.rest.StorjRestClient addShardToFrame
3 < ETag: W/"2b-qjUNgeYaw21Ju2Ryy07hig"
INFO: Attempting to negotiate shard contract, attempt 2 of 8
3 < Access-Control-Allow-Credentials: true
3 < Connection: keep-alive
3 < Vary: Origin
3 < Content-Length: 43
3 < Date: Mon, 22 Aug 2016 18:10:20 GMT
3 < X-Powered-By: Express
3 < Content-Type: application/json; charset=utf-8
3 < 
{"error":"No storage offers were received"}
4 * Client out-bound request
4 > PUT http://api.storj.io/frames/57bb3ffdc7f1854e44a56085
4 > Accept: application/json
4 > Authorization: basic XXX
4 > Content-Type: application/json
{"index":0,"hash":"b3de04e77ccc982070be76c56cc71015d3e13ea8","size":136356,"tree":["502fb33e68851a4a05d6055d73d3ddd59b6cbb55","5b6b5fc81cc721fab5fe5fba9cf232437084437f","446a96efb7cb2f90083e781340d71802d25fcbb7","20d4db024df34eef03c39a7138f67a99bd48bfaf","37886fce0dd47ac50240dcc9fcc7d26c3ae9faec","296be770058c067e7c5d62000499f184e937cacd","f7b5850fb835a471fdcad6d677b3da6702544f88","a30de95c04ff3ba2712227b32ae340649a6ab3be"],"challenges":["f7b7c6dd86152ac41b6555f959c46425","7623b13572d6577da28a7f1fb3fcc1a4","cca4e6c196e1aee5f155d50df38ae503","d57c3518b9416bca545b9f5d493a0136","6a5e6fcaefbf1a6ab48de8b8ded04daa","3b4d70dbb7a96e1e63c6a4cb4e3eb1a2","edca9a987345aee881481a2cb0ca7258","e28c7d52eec776c910af144e2724c5df"]}
4 * Client in-bound response
4 < 500
4 < Server: nginx/1.10.0
4 < ETag: W/"2b-qjUNgeYaw21Ju2Ryy07hig"
4 < Access-Control-Allow-Credentials: true
4 < Connection: keep-alive
4 < Vary: Origin
4 < Content-Length: 43
4 < Date: Mon, 22 Aug 2016 18:10:35 GMT
4 < X-Powered-By: Express
4 < Content-Type: application/json; charset=utf-8
4 < 
{"error":"No storage offers were received"}
Aug 22, 2016 7:10:36 PM storj.io.restclient.rest.StorjRestClient addShardToFrame
INFO: Failed with reason: PUT http://api.storj.io/frames/57bb3ffdc7f1854e44a56085 returned a response status of 500 Internal Server Error
Aug 22, 2016 7:10:36 PM storj.io.restclient.rest.StorjRestClient addShardToFrame
INFO: Attempting to negotiate shard contract, attempt 3 of 8
5 * Client out-bound request
5 > PUT http://api.storj.io/frames/57bb3ffdc7f1854e44a56085
5 > Accept: application/json
5 > Authorization: basic XXX
5 > Content-Type: application/json
{"index":0,"hash":"b3de04e77ccc982070be76c56cc71015d3e13ea8","size":136356,"tree":["502fb33e68851a4a05d6055d73d3ddd59b6cbb55","5b6b5fc81cc721fab5fe5fba9cf232437084437f","446a96efb7cb2f90083e781340d71802d25fcbb7","20d4db024df34eef03c39a7138f67a99bd48bfaf","37886fce0dd47ac50240dcc9fcc7d26c3ae9faec","296be770058c067e7c5d62000499f184e937cacd","f7b5850fb835a471fdcad6d677b3da6702544f88","a30de95c04ff3ba2712227b32ae340649a6ab3be"],"challenges":["f7b7c6dd86152ac41b6555f959c46425","7623b13572d6577da28a7f1fb3fcc1a4","cca4e6c196e1aee5f155d50df38ae503","d57c3518b9416bca545b9f5d493a0136","6a5e6fcaefbf1a6ab48de8b8ded04daa","3b4d70dbb7a96e1e63c6a4cb4e3eb1a2","edca9a987345aee881481a2cb0ca7258","e28c7d52eec776c910af144e2724c5df"]}
5 * Client in-bound response
5 < 200
5 < Server: nginx/1.10.0
5 < ETag: W/"10b-PTKzdFRCnVGtmBFbHz8vng"
5 < Access-Control-Allow-Credentials: true
5 < Connection: keep-alive
5 < Vary: Origin
5 < Content-Length: 267
5 < Date: Mon, 22 Aug 2016 18:10:43 GMT
5 < X-Powered-By: Express
5 < Content-Type: application/json; charset=utf-8
5 < 
{"hash":"b3de04e77ccc982070be76c56cc71015d3e13ea8","token":"24cff22601d1bfa1eb30e984d8875764bd9241bd","operation":"PUSH","farmer":{"protocol":"0.8.0","address":"hdd.siblin.ru","port":55720,"nodeID":"38b4a5724bf57ad6ab053b5ddca5c31a786e0622","lastSeen":1471889439938}}
6 * Client out-bound request
6 > GET http://api.storj.io/frames/57bb3ffdc7f1854e44a56085
6 > Accept: application/json
6 > Authorization: basic XXX
6 * Client in-bound response
6 < 200
6 < Server: nginx/1.10.0
6 < ETag: W/"a6-N2gYmh45hIqgNVg7OphCzQ"
6 < Access-Control-Allow-Credentials: true
6 < Connection: keep-alive
6 < Vary: Origin
6 < Content-Length: 166
6 < Date: Mon, 22 Aug 2016 18:10:43 GMT
6 < X-Powered-By: Express
6 < Content-Type: application/json; charset=utf-8
6 < 
{"user":"nutterzuk@gmail.com","shards":["57bb401c56123d683770e7f8"],"size":136356,"locked":false,"created":"2016-08-22T18:10:05.181Z","id":"57bb3ffdc7f1854e44a56085"}
Aug 22, 2016 7:10:48 PM storj.io.client.websockets.WebsocketShardSender onClose
INFO: Websocket closed with reasonCloseReason[1000,Consignment completed]
7 * Client out-bound request
7 > POST http://api.storj.io/buckets/57b99b136738047f2c421cf2/files
7 > Accept: application/json
7 > Authorization: basic XXX
7 > Content-Type: application/json
{"mimetype":"image/jpeg","filename":"cat.jpg","size":136368,"frame":"57bb3ffdc7f1854e44a56085"}
7 * Client in-bound response
7 < 200
7 < Server: nginx/1.10.0
7 < ETag: W/"d9-WKaN68oWaiDwEXOm3GJjtw"
7 < Access-Control-Allow-Credentials: true
7 < Connection: keep-alive
7 < Vary: Origin
7 < Content-Length: 217
7 < Date: Mon, 22 Aug 2016 18:10:47 GMT
7 < X-Powered-By: Express
7 < Content-Type: application/json; charset=utf-8
7 < 
{"bucket":"57b99b136738047f2c421cf2","frame":"57bb3ffdc7f1854e44a56085","name":"cat.jpg","renewal":"2016-11-20T18:10:47.705Z","mimetype":"image/jpeg","filename":"cat.jpg","id":"57bb4027c7f1854e44a5608e","size":136356}
Aug 22, 2016 7:10:48 PM storj.io.client.DefaultStorjClient downloadFile
INFO: C:\Users\steve\AppData\Local\Temp\temp3916252239112554302encrypted
8 * Client out-bound request
8 > POST http://api.storj.io/buckets/57b99b136738047f2c421cf2/tokens
8 > Accept: application/json
8 > Authorization: basic XXX
8 > Content-Type: application/json
{"operation":"PULL"}
8 * Client in-bound response
8 < 201
8 < Server: nginx/1.10.0
8 < ETag: W/"f0-dh+E1OyDZaEC23OhIRdxTw"
8 < Access-Control-Allow-Credentials: true
8 < Connection: keep-alive
8 < Vary: Origin
8 < Content-Length: 240
8 < Date: Mon, 22 Aug 2016 18:10:47 GMT
8 < X-Powered-By: Express
8 < Content-Type: application/json; charset=utf-8
8 < 
{"bucket":"57b99b136738047f2c421cf2","operation":"PULL","expires":"2016-08-22T18:15:47.917Z","token":"84c1603a0beb3f1f7daed20bb54fc06add88725f8af940027151e0e9bd472e69","id":"84c1603a0beb3f1f7daed20bb54fc06add88725f8af940027151e0e9bd472e69"}
9 * Client out-bound request
9 > GET http://api.storj.io/buckets/57b99b136738047f2c421cf2/files/57bb4027c7f1854e44a5608e?limit=10&skip=0
9 > Accept: application/json
9 > Authorization: basic XXX
9 > x-token: 84c1603a0beb3f1f7daed20bb54fc06add88725f8af940027151e0e9bd472e69
9 * Client in-bound response
9 < 200
9 < Server: nginx/1.10.0
9 < ETag: W/"120-vH9jhfPzORcq5kHMt9c0Qg"
9 < Access-Control-Allow-Credentials: true
9 < Connection: keep-alive
9 < Vary: Origin
9 < Content-Length: 288
9 < Date: Mon, 22 Aug 2016 18:10:50 GMT
9 < X-Powered-By: Express
9 < Content-Type: application/json; charset=utf-8
9 < 
[{"token":"e4201dc3a6cb062fa992b5f43724722ca3833fb0","hash":"b3de04e77ccc982070be76c56cc71015d3e13ea8","farmer":{"protocol":"0.8.0","address":"server.remsysuk.com","port":4000,"nodeID":"b9ff536a3a750c9ae6c30b5ea3c5c9d70915ef80","lastSeen":1471889448311},"operation":"PULL","size":136356}]
ws://server.remsysuk.com:4000
{"token":"e4201dc3a6cb062fa992b5f43724722ca3833fb0","hash":"b3de04e77ccc982070be76c56cc71015d3e13ea8","operation":"PULL"}

**Comment by bookchin** [comment] 2016-08-25 22:23
@NutterzUK trying to catch up here as this is the last issue I'd like to resolve before we merge and publish 3.1.0...

In no particular order:

* If you (or someone else) upload the same file (with the same hash) more than once and get a different farmer, when you go ask for a download token you may get any of them.
* I'm pretty confident that https://github.com/Storj/core/blob/db24a6c653e6653cb4844ef3374aadf69f3dcd13/lib/data-channels/server.js#L286 is not the issue as this simply checks if the connection is still open before trying to send data over it
* Your  code for the websocket looks right to me, but I'm not experienced with Java - however if you are saying that you can download with the CLI, then I tend to think that it *is* something on your end

It's strange because this really is pretty straightforward:

1. Open the connection: https://github.com/Storj/core/blob/master/lib/data-channels/client.js#L32-L35
2. Listen for message and close events: https://github.com/Storj/core/blob/master/lib/data-channels/readable-stream.js#L26-L33
3. Send authorization frame: https://github.com/Storj/core/blob/master/lib/data-channels/readable-stream.js#L64-L70

The fact that the remote host **does** close the connection with a `1000 NORMAL` status, indicates that she _thinks_ she sent you all the data. You mentioned there is a wait time before this happens - is that wait long enough to indicate the the bytes are getting transferred? Have you tried using something like [WireShark](https://www.wireshark.org/#download) to try and debug?

Let me know what I can do to help.

**Comment by super3** [comment] 2016-08-29 01:00
From @NutterzUK "I just totally changed the websocket library i'm using. And it worked out of the box."

**Closed by super3** 2016-08-29 01:00 UTC
Labels: bug, in progress
