### ISSUE TITLE
Upload of multiple files fails, hangs or errors

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core#384] opened 2016-08-30 09:50 UTC
### Package Versions
```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core
        └── storj --version@3.1.0
```

### Expected Behavior

clean exit.

### command

```

command: storj -k meije0612 -r 10 upload-file 57af47613a91dae863d26903 H:\Meije\ScientificArticles\*

```

### Error

```
[Tue Aug 30 2016 11:41:47 GMT+0200 (W. Europe Daylight Time)] [info]   [ ‘Developmental’-policies-and-rent-comparing-Russia-and-Sub-Saharan-Africa_2016_Commonwealth-and-Comparative-Politics.pdf ] Encryption key saved to keyring.
 [Tue Aug 30 2016 11:41:47 GMT+0200 (W. Europe Daylight Time)] [info]   [ ‘Developmental’-policies-and-rent-comparing-Russia-and-Sub-Saharan-Africa_2016_Commonwealth-and-Comparative-Politics.pdf ] File successfully stored in bucket.
 [Tue Aug 30 2016 11:41:47 GMT+0200 (W. Europe Daylight Time)] [info]   Name: ‘Developmental’-policies-and-rent-comparing-Russia-and-Sub-Saharan-Africa_2016_Commonwealth-and-Comparative-Politics.pdf, Type: application/pdf, Size: 819720 bytes, ID: 57c554d91fc335070991d560
 [Tue Aug 30 2016 11:41:47 GMT+0200 (W. Europe Daylight Time)] [info]   Establishing 10 mirrors per shard for redundancy
 [Tue Aug 30 2016 11:41:47 GMT+0200 (W. Europe Daylight Time)] [info]   This can take a while, so grab a cocktail...
 [Tue Aug 30 2016 11:42:03 GMT+0200 (W. Europe Daylight Time)] [info]   Shard 686146f1cb03e3e4db9001245969b5afb84e73fc mirrored by 0 nodes

C:\WINDOWS\system32>

```

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

### command

```

 storj -k meije0612 -r 20  upload-file 57af47613a91dae863d26903 H:\Meije\ScientificArticles\*

```

### Error

```
ssia-and-Sub-Saharan-Africa_2016_Commonwealth-and-Comparative-Politics.pdf ] File successfully stored in bucket.
 [Tue Aug 30 2016 11:59:18 GMT+0200 (W. Europe Daylight Time)] [info]   Name: ‘Developmental’-policies-and-rent-comparing-Russia-and-Sub-Saharan-Africa_2016_Commonwealth-and-Comparative-Politics.pdf, Type: application/pdf, Size: 819720 bytes, ID: 57c558f4f0ea649f5e603278
 [Tue Aug 30 2016 11:59:18 GMT+0200 (W. Europe Daylight Time)] [info]   Establishing 20 mirrors per shard for redundancy
 [Tue Aug 30 2016 11:59:18 GMT+0200 (W. Europe Daylight Time)] [info]   This can take a while, so grab a cocktail...
 [Tue Aug 30 2016 11:59:19 GMT+0200 (W. Europe Daylight Time)] [error]  Refusing to create more than 12 mirrors

C:\WINDOWS\system32>

```
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

### Steps to Reproduce

Upload a folder containing multiple files and add redundancy (-r). The task will either just exit on it's own without giving any error, or it will hang somewhere during the upload, or it will exit with an error.

**Comment by MeijeSibbel** [comment] 2016-08-30 09:52
This issue only occurs when adding '-r', when removing the mirror call the process does not exit.

**Comment by MeijeSibbel** [comment] 2016-08-30 10:17
If -r is removed, the upload hangs.

**Comment by littleskunk** [comment] 2016-08-30 12:00
The hanging upload is duplicate: #357

This is fixed with the new core release but give us farmer a few days to update. GUI farmer can't update at the moment. Please try again in 2 or 3 days.

I will keep this issue open for the moment. I am not sure the process exit will be fixed as well.

**Comment by aleitner** [comment] 2016-08-30 15:51
Also storj bridge server hasn't been updated for the mirroring

**Comment by MeijeSibbel** [comment] 2016-08-30 23:06
Something strange is going on with the hanging uploads, i ran the automated script to update to core 3.1.0, after that i started to try to upload all sort of large files countless times but none of then succeed, all the uploads hanged on the last 2 shards. So i though what the heck and i tried to install Storj again with the automated script, but this time it returned a message 'failed to install storj, try manual install' then i tried to install Storj using 'npm install storj --global', which also failed, and i i got the errors below:

C:\WINDOWS\system32>npm install storj --global
npm ERR! tar.unpack error reading C:\WINDOWS\system32\storj
npm ERR! addLocal Could not install C:\WINDOWS\system32\storj
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "storj" "--global"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! 0-byte tarball
npm ERR! Please run `npm cache clean`
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log

C:\WINDOWS\system32

So i went and deleted the Storj file at C:\WINDOWS\system32\storj and used 'npm install storj --global' again to install Storj. This time it worked and Storj was installed correctly. After this i resumed my attempts to upload large files and all of a sudden i am able to upload large files without any issues!. Is it possible that something corrupts the storj file C:\WINDOWS\system32\storj ?

**Comment by MeijeSibbel** [comment] 2016-08-30 23:10
New error when uploading a file:

storj -k meije0612 -r 10 -c 99 upload-file 57b05629905cfece30b430f0 H:\Meije\Movies\file.avi

 [Wed Aug 31 2016 00:41:49 GMT+0200 (W. Europe Daylight Time)] [info]   Establishing 10 mirrors per shard for redundancy
 [Wed Aug 31 2016 00:41:49 GMT+0200 (W. Europe Daylight Time)] [info]   This can take a while, so grab a cocktail...
 [Wed Aug 31 2016 00:43:49 GMT+0200 (W. Europe Daylight Time)] [error]  <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>


C:\WINDOWS\system32>

**Comment by MeijeSibbel** [comment] 2016-08-31 00:27
command: storj -k meije0612 upload-file 57af3a1e8f266a7d4e391055 C:\Users\Meije\Desktop\*

error:

[Wed Aug 31 2016 02:21:18 GMT+0200 (W. Europe Daylight Time)] [info]   Name: 0_ContMech_Excercises_2015.pdf, Type: application/pdf, Size: 1436767 bytes, ID: 57c62301ba9b85b115d6888a
 [Wed Aug 31 2016 02:21:18 GMT+0200 (W. Europe Daylight Time)] [info]   4 of 214 files uploaded
 [Wed Aug 31 2016 02:21:18 GMT+0200 (W. Europe Daylight Time)] [info]   Encrypting file "C:/Users/Meije/Desktop/0-1323"
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)

C:\WINDOWS\System32>

**Comment by MeijeSibbel** [comment] 2016-09-01 16:51
error:

 [Thu Sep 01 2016 18:39:04 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 43af968eacdcb28326d6c4e733f04df0e196aa6c (retry: 24)
 [Thu Sep 01 2016 18:39:20 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to upload shard...
 [Thu Sep 01 2016 18:39:20 GMT+0200 (W. Europe Daylight Time)] [warn]   [ r_1007000.torrent ] Error occurred. Triggering cleanup...
 [Thu Sep 01 2016 18:39:20 GMT+0200 (W. Europe Daylight Time)] [info]   [ r_1007000.torrent ] Cleaning up...
 [Thu Sep 01 2016 18:39:20 GMT+0200 (W. Europe Daylight Time)] [info]   [ r_1007000.torrent ] Finished cleaning!
 [Thu Sep 01 2016 18:39:20 GMT+0200 (W. Europe Daylight Time)] [error]  [ undefined ] A file has failed to upload: Error: No storage offers were received

C:\WINDOWS\system32>

**Comment by MeijeSibbel** [comment] 2016-09-01 21:59
error: 

 [Thu Sep 01 2016 23:31:21 GMT+0200 (W. Europe Daylight Time)] [warn]   [ [Cobalt(III)-EDTA]sup-sup-reduction-by-thermophilic-methanogen-Methanothermobacter-thermautotrophicus_2015_Chemical-Geology.pdf ] Error occurred. Triggering cleanup...
 [Thu Sep 01 2016 23:31:21 GMT+0200 (W. Europe Daylight Time)] [info]   [ [Cobalt(III)-EDTA]sup-sup-reduction-by-thermophilic-methanogen-Methanothermobacter-thermautotrophicus_2015_Chemical-Geology.pdf ] Cleaning up...
 [Thu Sep 01 2016 23:31:21 GMT+0200 (W. Europe Daylight Time)] [info]   [ [Cobalt(III)-EDTA]sup-sup-reduction-by-thermophilic-methanogen-Methanothermobacter-thermautotrophicus_2015_Chemical-Geology.pdf ] Finished cleaning!
 [Thu Sep 01 2016 23:31:21 GMT+0200 (W. Europe Daylight Time)] [error]  [ undefined ] A file has failed to upload: Error: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>


C:\WINDOWS\system32>

**Comment by MeijeSibbel** [comment] 2016-09-02 12:48
![2016-09-02](https://cloud.githubusercontent.com/assets/11735738/18204301/4fbaea2c-711c-11e6-85b7-75928b30208d.png)

**Comment by bookchin** [comment] 2016-09-02 13:26
Thanks for the thorough information, we are working in this. 

Also, please be mindful that many of us get email notifications for all activity on GitHub. ;)

**Comment by bookchin** [comment] 2016-09-12 14:50
Duplicate of #410

**Closed by bookchin** 2016-09-12 14:50 UTC
Labels: bug
