### ISSUE TITLE
File upload error (core v.3.0.3) - windows 10

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core#346] opened 2016-08-18 21:17 UTC
### Package Versions

npm --version: 2.15.9

node --version: 4.5.0

core version : 3.0.3

OS: windows 10 home edition

### Expected Behavior

clean exit

### Actual Behavior

[Thu Aug 18 2016 22:22:11 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 18de713f8c1eeb63837d08b8bf87782c6bce5a20 to frame
 [Thu Aug 18 2016 22:22:13 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to upload shard...
 [Thu Aug 18 2016 22:22:14 GMT+0200 (W. Europe Daylight Time)] [warn]   Error occured. Triggering cleanup...
 [Thu Aug 18 2016 22:22:14 GMT+0200 (W. Europe Daylight Time)] [info]   Cleaning up...
fs.js:758
  return binding.rmdir(pathModule._makeLong(path));
                 ^

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\meije\AppData\Local\Temp\storj-191604aPQcxuOYX8j'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at _rmdirRecursiveSync (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\node_modules\tmp\lib\tmp.js:285:10)
    at _cleanupCallback (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\node_modules\tmp\lib\tmp.js:409:5)
    at cleanup (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\bin\storj.js:478:11)
    at UploadState.callback (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\bin\storj.js:507:23)
    at C:\Users\meije\AppData\Roaming\npm\node_modules\storj\lib\bridge-client\index.js:496:22
    at C:\Users\meije\AppData\Roaming\npm\node_modules\storj\lib\bridge-client\index.js:341:16
    at Request._callback (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\lib\bridge-client\index.js:922:14)
    at Request.self.callback (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\node_modules\request\request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\node_modules\request\request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\node_modules\request\request.js:965:12)

C:\WINDOWS\system32>storj --version
3.0.3

```

### Steps to Reproduce

upload a file

**Comment by 1credit** [comment] 2016-08-18 21:25
Also having basic loading issues under linux:

http://puu.sh/qG76Q/e9225dda5e.png

The target file was a bit over 2GB in size.  Running Storj 3.0.3, node v4.4.7.

**Comment by bookchin** [comment] 2016-08-18 21:35
Pretty sure that's a stack trace and it's helpful.

**Comment by 1credit** [comment] 2016-08-18 21:42
My example had NO error message, it simply ended with a return to the command prompt.

**Comment by bookchin** [comment] 2016-08-18 22:44
This is actually a duplicate of #347 - the only difference is that after the first failure, another operation succeeded (even though the whole routine should stop) and it tried to load the temp shard after it had already been cleaned. Closing this one, let's track at the other.

**Closed by bookchin** 2016-08-18 22:44 UTC
