### ISSUE TITLE
Invalid Array Buffer Length

### ISSUE THREAD

**Issue by super3** [Storj/core#396] opened 2016-08-31 18:01 UTC
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
├── storj@3.1.0
└─┬ storj-bridge-client@0.4.3
  └── storj@0.6.16
```

Replace the values below using the output from `node --version`.

```
v5.1.0
```

I'm using the wrong version number. But I think this is reproducible across versions. Will downgrade and try again.

### Expected Behavior

Upload proceeds until completion. 

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
 [Wed Aug 31 2016 13:44:57 GMT-0400 (Eastern Daylight Time)] [info]   [ dump2 ] Storing file, hang tight!
 [Wed Aug 31 2016 13:44:57 GMT-0400 (Eastern Daylight Time)] [debug]  Request: {"baseUrl":"https://api.staging.storj.io","uri":"/frames","method":"POST","json":{"__nonce":"93b2e57b-6ea0-4293-98e7-935e36dd5864"},"headers":{"x-pubkey":"03026d072b0612c7b419c16bfd811760e34551e9422a1c5a95d2516896b1fc124f","x-signature":"304502207a7ac5ac33183764b1ed96ad2e060b022c6399b0fb0496046d50299628f82611022100ed9d3ce15431e0c4a501cd7d64d4557a8c1af10741789c9d228a09e312a96f16"}}
 [Wed Aug 31 2016 13:44:57 GMT-0400 (Eastern Daylight Time)] [debug]  Body: {"user":"cats@storj.io","shards":[],"size":0,"locked":false,"created":"2016-08-31T17:44:46.990Z","id":"57c7178e274ee8b3253b69e2"}
 [Wed Aug 31 2016 13:44:57 GMT-0400 (Eastern Daylight Time)] [info]   Trying to upload shard C:\Users\work\AppData\Local\Temp\c6a8e567c74f index 0
 [Wed Aug 31 2016 13:45:12 GMT-0400 (Eastern Daylight Time)] [info]   Hash for this shard is: 20aa0cf37b5d71653333eb4a718f60f1d4f38262
 [Wed Aug 31 2016 13:45:51 GMT-0400 (Eastern Daylight Time)] [info]   Audit generation for shard done.
 [Wed Aug 31 2016 13:45:51 GMT-0400 (Eastern Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Wed Aug 31 2016 13:45:51 GMT-0400 (Eastern Daylight Time)] [info]   Querying bridge for contract for 20aa0cf37b5d71653333eb4a718f60f1d4f38262 (retry: 0)
 [Wed Aug 31 2016 13:45:51 GMT-0400 (Eastern Daylight Time)] [debug]  Request: {"baseUrl":"https://api.staging.storj.io","uri":"/frames/57c7178e274ee8b3253b69e2","method":"PUT","json":{"hash":"20aa0cf37b5d71653333eb4a718f60f1d4f38262","size":2147483648,"index":0,"challenges":["ddcfce75440de584e22f45ba52b62f04c76e8ace1378881a8a55dd44ed5a0242","8bf9f20a9a63d2fca8e5149ea56e76a11d1ebcb4207f6a770a13293596a08e5f","e207a7b5048c1dbdcaaa97a09dad130e648a6a997c67d9220cb2abcfddf62b77"],"tree":["e6983a5f9d0936650f37e23e57929bb30e84a6c4","beacf5c7e9173c7c72a397ddb5f96946858fdc38","2212628d64dd521af144932157bf5022b495d6cc","b472a266d0bd89c13706a4132ccfb16f7c3b9fcb"],"exclude":[],"__nonce":"3c770145-5f8b-4a02-98a1-6c339cdc35e2"},"headers":{"x-pubkey":"03026d072b0612c7b419c16bfd811760e34551e9422a1c5a95d2516896b1fc124f","x-signature":"304502206b4dbb60d53756a985cc256e5d362df48db78558b05ce9cf4be4d80e73f0762b022100958896121bfa61f8f13c99fc2bc14224cdb7498b870e2819982760c783831e21"}}
 [Wed Aug 31 2016 13:45:52 GMT-0400 (Eastern Daylight Time)] [debug]  Body: {"hash":"20aa0cf37b5d71653333eb4a718f60f1d4f38262","token":"984b8f5cad136a1091adb4717dafd7e8d014558f","operation":"PUSH","farmer":{"protocol":"0.8.0-STAGING","address":"104.196.127.153","port":4000,"nodeID":"061bc46c36e33747e622639ecddfb8422a76746b","lastSeen":1472665541408}}
 [Wed Aug 31 2016 13:45:52 GMT-0400 (Eastern Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.0-STAGING","address":"104.196.127.153","port":4000,"nodeID":"061bc46c36e33747e622639ecddfb8422a76746b","lastSeen":1472665541408}
 [Wed Aug 31 2016 13:45:52 GMT-0400 (Eastern Daylight Time)] [info]   Data channel opened, transferring shard...
 [Wed Aug 31 2016 13:48:15 GMT-0400 (Eastern Daylight Time)] [info]   Shard transfer completed! 49 remaining...
 [Wed Aug 31 2016 13:48:16 GMT-0400 (Eastern Daylight Time)] [info]   Trying to upload shard C:\Users\work\AppData\Local\Temp\2a8bad9d2e07 index 1
 [Wed Aug 31 2016 13:49:30 GMT-0400 (Eastern Daylight Time)] [info]   Hash for this shard is: 5378db53d7aeff8913801fb35d7f590fa395d949
 [Wed Aug 31 2016 13:51:08 GMT-0400 (Eastern Daylight Time)] [info]   Audit generation for shard done.
 [Wed Aug 31 2016 13:51:08 GMT-0400 (Eastern Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Wed Aug 31 2016 13:51:08 GMT-0400 (Eastern Daylight Time)] [info]   Querying bridge for contract for 5378db53d7aeff8913801fb35d7f590fa395d949 (retry: 0)
 [Wed Aug 31 2016 13:51:08 GMT-0400 (Eastern Daylight Time)] [debug]  Request: {"baseUrl":"https://api.staging.storj.io","uri":"/frames/57c7178e274ee8b3253b69e2","method":"PUT","json":{"hash":"5378db53d7aeff8913801fb35d7f590fa395d949","size":2147483648,"index":1,"challenges":["1a2e42f6136816de43c1a7b572fe4ab1cce9346d0c3b5a2ca9e6a43f0744aa50","83a4d444b9f557c2504578c61eb5443c4b31c2e7543c3351922543e57e66a05d","a49e1230d5bf43e8fcb39238b74fab1cf91e27d22d2e49ca4a715b52eeb2f5c0"],"tree":["144bda546d289c7b95dbe3fc28d1ea25c40eb290","102554b9be43252c52cb1bbc36e1597355721910","8fff483aaa1cda6f926d138d872e1240deb4eaae","b472a266d0bd89c13706a4132ccfb16f7c3b9fcb"],"exclude":[],"__nonce":"14e7f503-1fec-4384-be33-6080598768cf"},"headers":{"x-pubkey":"03026d072b0612c7b419c16bfd811760e34551e9422a1c5a95d2516896b1fc124f","x-signature":"3045022016aedbd755cca191601d39c3198a46c127e6673840f5bea17b91f507569e419c022100a4d5b7c2aaf5565b9e63e1902c5245d05a0d3d18d6e47afdf5e4c3742aaa0878"}}
 [Wed Aug 31 2016 13:51:09 GMT-0400 (Eastern Daylight Time)] [debug]  Body: {"hash":"5378db53d7aeff8913801fb35d7f590fa395d949","token":"a1320812f31a4a76cc6d73c42d1588751d1ec1b7","operation":"PUSH","farmer":{"protocol":"0.8.0-STAGING","address":"104.196.117.75","port":4000,"nodeID":"6412ecb5763de95452ebf3273b4fa43f746efb74","lastSeen":1472665858389}}
 [Wed Aug 31 2016 13:51:09 GMT-0400 (Eastern Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.0-STAGING","address":"104.196.117.75","port":4000,"nodeID":"6412ecb5763de95452ebf3273b4fa43f746efb74","lastSeen":1472665858389}
 [Wed Aug 31 2016 13:51:09 GMT-0400 (Eastern Daylight Time)] [info]   Data channel opened, transferring shard...
buffer.js:98
    const ui8 = new Uint8Array(size);
                ^

RangeError: Invalid array buffer length
    at new ArrayBuffer (native)
    at new Uint8Array (native)
    at allocate (buffer.js:98:17)
    at new Buffer (buffer.js:49:12)
    at allocNewPool (fs.js:1685:10)
    at ReadStream._read (fs.js:1784:5)
    at ReadStream.Readable.read (_stream_readable.js:328:10)
    at readableAddChunk (_stream_readable.js:147:16)
    at ReadStream.Readable.push (_stream_readable.js:110:10)
    at onread (fs.js:1822:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:614:17)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Upload 100 GB file for the lulz
2. Crashes after 1-2 shards

**Comment by super3** [comment] 2016-08-31 20:17
Downgraded to 4.4.5 and was able to reproduce the error.

**Comment by MeijeSibbel** [comment] 2016-09-01 17:02
I want to suggest the Storj team to always do one or two 100GB uploads before each core release because if a bug is present, it will 100% guaranteed surface with these very large files. I have been running core for at least a month now and have never managed to upload a 100GB file successfully, a 100GB upload test at the Storj office should become a routine task.

**Comment by littleskunk** [comment] 2016-09-03 17:14
We can't test everything with our own little farmer network. The last 1GB upload problem had to do with tunnel nodes not sending data channel close. We are not able to predict issues like that. That is the reason we are running a test group. The cummunity has a better farmer network than we could ever setup. That way we find all issues.

**Comment by MeijeSibbel** [comment] 2016-09-08 14:23
same error: 

command: 

1- C:\Windows\system32>set temp=D:\temp
2- C:\Windows\system32>storj -k meije0612 -c 20 upload-file 57af3a1e8f266a7d4e391055 D:\20GB

error:

[Thu Sep 08 2016 16:17:34 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
[Thu Sep 08 2016 16:17:38 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: 00a2abec6805fec54157f2d674ef23d037d645fe
[Thu Sep 08 2016 16:17:39 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
[Thu Sep 08 2016 16:17:39 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
[Thu Sep 08 2016 16:17:39 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for e74e03f2209b1bf5a2010da06d98b39a79d21e08 (retry: 0)
[Thu Sep 08 2016 16:17:55 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for e74e03f2209b1bf5a2010da06d98b39a79d21e08 (retry: 1)
[Thu Sep 08 2016 16:18:11 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for e74e03f2209b1bf5a2010da06d98b39a79d21e08 (retry: 2)
[Thu Sep 08 2016 16:18:20 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for e74e03f2209b1bf5a2010da06d98b39a79d21e08 (retry: 3)
[Thu Sep 08 2016 16:18:24 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.0","address":"95.77.247.150","port":12962,"no
eID":"e42234e4cae9695135424acf0ab10d93636e841f","lastSeen":1473344300124}
[Thu Sep 08 2016 16:18:25 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
[Thu Sep 08 2016 16:18:42 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
[Thu Sep 08 2016 16:18:42 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
[Thu Sep 08 2016 16:18:42 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 00a2abec6805fec54157f2d674ef23d037d645fe (retry: 0)
[Thu Sep 08 2016 16:19:05 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 00a2abec6805fec54157f2d674ef23d037d645fe (retry: 1)
uffer.js:25
   const ui8 = new Uint8Array(size);
               ^

angeError: Invalid array buffer length
   at new ArrayBuffer (native)
   at new Uint8Array (native)
   at createBuffer (buffer.js:25:17)
   at allocate (buffer.js:158:12)
   at new Buffer (buffer.js:56:12)
   at allocNewPool (fs.js:1602:10)
   at ReadStream._read (fs.js:1701:5)
   at ReadStream.Readable.read (_stream_readable.js:336:10)
   at readableAddChunk (_stream_readable.js:154:18)
   at ReadStream.Readable.push (_stream_readable.js:111:10)
   at onread (fs.js:1739:12)
   at FSReqWrap.wrapper [as oncomplete] (fs.js:576:17)

:\Windows\system32>

**Comment by aleitner** [comment] 2016-09-08 15:15
@MeijeSibbel your concurrency is at 20. You're adding too much data into memory which is causing this error. Shawn is doing the same thing. We're gonna limit the concurrency.

See this issue
https://github.com/nodejs/node/issues/3543

**Comment by super3** [comment] 2016-09-08 15:54
Don't believe that is correct. I set both file and shard concurrency to 1
while testing this.

**Comment by aleitner** [comment] 2016-09-08 15:59
Gordon says prove it

**Comment by bookchin** [comment] 2016-09-08 16:00
:trollface:

**Comment by super3** [comment] 2016-09-08 16:13
How much we betting on this? I'm uploading a 100 GB file, which would give
you about ~3.5 GB shards based on the new shard calculations. Seems to
error out at the large of a shard size.

I can try it myself but it's going to take me bit to SSH a VM with my
phone. Can you generate and attempt to upload a 100 GB file for me?

**Comment by aleitner** [comment] 2016-09-08 16:16
How much ram is on your computer?

**Comment by super3** [comment] 2016-09-08 16:19
Trying to remember what computer I tried this on. I believe it was the
office window$ so 8-16 GB. Going to build up a VM.

**Comment by aleitner** [comment] 2016-09-08 16:20
If it's 8gb then 2 shards would cause this issue

**Comment by MeijeSibbel** [comment] 2016-09-08 21:44
C:\Windows\system32>set temp=D:\temp

C:\Windows\system32>storj -k meije0612 -c 1 upload-file 57af3a1e8f266a7d4e391055 D:\20GB

 [Thu Sep 08 2016 23:16:34 GMT+0200 (W. Europe Daylight Time)] [info]   1 file(s) to upload.
 [Thu Sep 08 2016 23:16:35 GMT+0200 (W. Europe Daylight Time)] [info]   Generating encryption key...
 [Thu Sep 08 2016 23:16:35 GMT+0200 (W. Europe Daylight Time)] [info]   Encrypting file "D:/20GB"
 [Thu Sep 08 2016 23:41:00 GMT+0200 (W. Europe Daylight Time)] [info]   [ 20GB ] Encryption complete!
 [Thu Sep 08 2016 23:41:00 GMT+0200 (W. Europe Daylight Time)] [info]   [ 20GB ] Creating storage token...
 [Thu Sep 08 2016 23:41:01 GMT+0200 (W. Europe Daylight Time)] [info]   [ 20GB ] Storing file, hang tight!
 [Thu Sep 08 2016 23:41:02 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard D:\temp\582b728fbb4d index 0
 [Thu Sep 08 2016 23:41:26 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: b2845d04348edc1b6918c9c7b475092c5aaf70fc
 [Thu Sep 08 2016 23:42:23 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Thu Sep 08 2016 23:42:23 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Thu Sep 08 2016 23:42:23 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for b2845d04348edc1b6918c9c7b475092c5aaf70fc (retry: 0)
 [Thu Sep 08 2016 23:43:00 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for b2845d04348edc1b6918c9c7b475092c5aaf70fc (retry: 1)
buffer.js:25
    const ui8 = new Uint8Array(size);
                ^

RangeError: Invalid array buffer length
    at new ArrayBuffer (native)
    at new Uint8Array (native)
    at createBuffer (buffer.js:25:17)
    at allocate (buffer.js:158:12)
    at new Buffer (buffer.js:56:12)
    at allocNewPool (fs.js:1602:10)
    at ReadStream._read (fs.js:1701:5)
    at ReadStream.Readable.read (_stream_readable.js:336:10)
    at readableAddChunk (_stream_readable.js:154:18)
    at ReadStream.Readable.push (_stream_readable.js:111:10)
    at onread (fs.js:1739:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:576:17)

C:\Windows\system32>

**Comment by super3** [comment] 2016-09-08 22:19
Replicated by @MeijeSibbel.

Here are my suggestions:
1) Let the user manually override the shard size to avoid this
2) Handle and restart the upload with a smaller shard size

**Comment by MeijeSibbel** [comment] 2016-09-08 22:21
I can confirm that it is indeed a lack of memory issue, once the memory reaches 100% it crashes.

**Closed** 2016-09-09 14:25 UTC
Labels: bug
