### ISSUE TITLE
You are too low on memory

### ISSUE THREAD

**Issue by 1credit** [Storj/core#467] opened 2016-09-28 02:57 UTC
### Package Versions

Replace the values below using the output from `npm list storj`. Use `npm list -g storj` if installed globally.

```
Storj 1.0.5 (@next as of 9/27/16 9:54pm CST6CDT)
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```
### Expected Behavior

Upload to run clean

```

```
### Actual Behavior

While uploading a 6.5GB file, I received the message "You are too low on memory! error:

http://puu.sh/rqh7d/eb4c7438b0.png

System has 32GB of memory with (4) storjshare-cli instances running.  Top indicated about 16GB of memory available.  Storj command was using around 7GB with 5.9GB resident.

Note the upload appears to be continuing.  /tmp filesystem is only 13% full (64GB /tmp).

```

```
### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.
1. ...
2. ...
3. ...

**Comment by aleitner** [comment] 2016-09-28 13:55
os.freemem is reporting that your memory is less than the shard size that is being transferred. I think there are issues with os.freemem() itself, htop displays a more accurate memory usage.

**Comment by littleskunk** [comment] 2016-09-28 14:14
I had the same problem. I would like to upload a 1GB shard with concurrency 1 but I have only 1,5GB free memory.

The beginning was fine. Shard encryption und the first bridge query are working. At that point core-cli needs 1GB memory. Only 0,5 free memory. Process stoped with that nice error message even if the needed memory is already locked for all further steps.

The problem is that the free memory is validated on each bridge query. I would expect only one validation at the beginning.

**Comment by aleitner** [comment] 2016-09-28 14:23
If you're running other processes while uploading, you're going to have varying memory usage during upload, thus we check free mem before every shard transfer. I'm thinking of integrating an event where whenever free mem goes low at any point of the upload process it terminates. As opposed to just checking before shard transfer

**Comment by littleskunk** [comment] 2016-09-28 15:05
Well in that case the validation should be:
Needed memory (shard size * concurrency) - already allocated memory <= free memory.

At the moment we ignore the already allocated memory.

**Comment by aleitner** [comment] 2016-09-28 17:48
Nodes got some serious garbage collection issues with streams at the moment https://github.com/nodejs/node/issues/6078

We'll be thinking about designs to help alleviate the massive memory usage issues

**Comment by 1credit** [comment] 2016-09-28 21:41
Problem is that I had PLENTY of free memory - only a 6.5GB file on a 32GB system, with htop reporting only 17MB in use - with the transfer working.  Note the upload is running, despite the error message.  This feels more like someone is doing 32 bit math instead of 64 bit (a bit of an opps for anyone with over 4GB of memory, and thats presuming unsigned 32bit integers).

**Comment by aleitner** [comment] 2017-03-16 18:41
This is no longer a problem in the C cli. We will eventually wrap c library with javascript to fix this

**Comment by bookchin** [comment] 2017-03-31 15:03
Closing in favor of https://github.com/Storj/core/issues/656

**Closed by bookchin** 2017-03-31 15:03 UTC
Labels: discussion
