### ISSUE TITLE
storj-farmer dies after unable to find a tunnel

### ISSUE THREAD

**Issue by phutchins** [Storj/core#90] opened 2016-05-11 13:30 UTC
### Package Versions

Replace the values below using the output from `npm list storj`.

```
storj-farmer@2.2.7 /Users/philip/.nvm/versions/node/v5.9.1/lib/node_modules/storj-farmer
└── storj@0.6.11
```

Replace the values below using the output from `node --version`.

```
v5.9.1
```

### Expected Behavior

```
I would expect the farmer to continue asking for a tunnel until it finds one.
```

### Actual Behavior

```
The farmer usually finds a tunnel on initial start. It renegotiates tunnels a number of times but eventually is unable to find a tunnel after going through the tunnel list it has and terminates. 
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Configure storj-farmer with forward set to true
2. Run storjfarm from command line
3. Wait

**Comment by gordonwritescode** [comment] 2016-05-18 18:30
I'm not sure that this is the behavior we really want. The `storjshare` program exiting after exhausting all options for discovering tunnels is by design. If we design it to continue asking the original seed for known tunnels even after the seed has responded back with all the tunneling nodes it's aware of, we need to consider frequency and the potential load on the default seed in the event that a large subset of nodes are unable to establish a tunnel.

In any case, this exit logic is not implemented here in core, but at the interface layer: https://github.com/Storj/storjshare-cli/blob/master/bin/farmer.js#L389-L394

Let's open this issue there, closing this one.

**Closed** 2016-05-18 18:31 UTC
Labels: discussion
